language: go
sudo: false
go:
  - 1.12.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/sshb0t-darwin-amd64
          - cross/sshb0t-darwin-amd64.md5
          - cross/sshb0t-darwin-amd64.sha256
          - cross/sshb0t-darwin-386
          - cross/sshb0t-darwin-386.md5
          - cross/sshb0t-darwin-386.sha256
          - cross/sshb0t-freebsd-amd64
          - cross/sshb0t-freebsd-amd64.md5
          - cross/sshb0t-freebsd-amd64.sha256
          - cross/sshb0t-freebsd-386
          - cross/sshb0t-freebsd-386.md5
          - cross/sshb0t-freebsd-386.sha256
          - cross/sshb0t-linux-arm
          - cross/sshb0t-linux-arm.md5
          - cross/sshb0t-linux-arm.sha256
          - cross/sshb0t-linux-arm64
          - cross/sshb0t-linux-arm64.md5
          - cross/sshb0t-linux-arm64.sha256
          - cross/sshb0t-linux-amd64
          - cross/sshb0t-linux-amd64.md5
          - cross/sshb0t-linux-amd64.sha256
          - cross/sshb0t-linux-386
          - cross/sshb0t-linux-386.md5
          - cross/sshb0t-linux-386.sha256
          - cross/sshb0t-solaris-amd64
          - cross/sshb0t-solaris-amd64.md5
          - cross/sshb0t-solaris-amd64.sha256
          - cross/sshb0t-windows-amd64
          - cross/sshb0t-windows-amd64.md5
          - cross/sshb0t-windows-amd64.sha256
          - cross/sshb0t-windows-386
          - cross/sshb0t-windows-386.md5
          - cross/sshb0t-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "A9QeY6UDN+vtmkqM+CHuMGDMqrGPXz4cMel2yO0QGe+CVnC7ou4sI0ttPnGjVHPhwwmRIGJqnaD5N3Zt7QCXMNMmfORRkyBsEFyaqcavVam0x/eugrl5hoaI9gia6QEcHIDJJKlrRihDFtvKJ98vt3e/ulbFMc4lntZ/Yjv50KlqrjSWQZWQp+yJcok9sE7GMCloQNg/D65MCmU092iEq8Di6rZaw+ZKHOu7FC5NVtO7/Qr2/hMGALQO6cSn0lBW4f6IytbPaTrH9i+uUHfmH3wda/zBkp6zIa9erRgpBc+SHErHtIAKLsPJD1zLyILd/unZkjwHQH/8RFYSCPEqXcoIsrgtra14IhSuZzzwu2E853Ayrh1Rh6kDav31aMqCPjT8pGuGJL1KFCVyV2Q4Ruxd05vtlPY7eNnnI+CiFZRwuJWQEHDwYpoEwC9etG/3Frqq0fdN5h6E4eww5cU9kg/zzWZpfUnnciR1TFis/mj2YWglY0Aqog+meKKrC7x4O60uP+2lCT9kVC+xEsQ8z1qR7htdHoy4RvJ1Q9U5SWq2qQ3JAOLFaHBNT1ha0cP57dD0MnU3MtHqd2Yhxqe7rRPb13jZDQmDDXkoFFpnphnQPEwyDrfpc5oXn7+Vv/+MAfQuchYONzOoBJdYlaOmR2X67yZwp3LvEkvKIwkZxEw="
